package in.succinct.beckn;

import org.json.simple.JSONArray;

public class CancellationReasons extends BecknObjectsWithId<Option>{

    public CancellationReasons() {
        super();
    }

    public CancellationReasons(JSONArray value) {
        super(value);
    }

    public CancellationReasons(String payload) {
        super(payload);
    }



    static final int TRIGGERS_RTO = 1;

    static final int USABLE_BY_BUYER_PARTY = 2 ;
    static final int USABLE_BY_SELLER_PARTY = 4 ;
    static final int USABLE_BY_LOGISTICS_PARTY = 8 ;


    static final int BUYER_PARTY_RESPONSIBLE_FOR_LOSSES = 32 ;
    static final int SELLER_PARTY_RESPONSIBLE_FOR_LOSSES = 64 ;
    static final int LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES = 128 ;


    static final int PART_CANCEL_APPLICABLE = 1024;



    public enum CancellationReasonCode {
        CANNOT_ACCEPT_UPDATED_PRICE(~TRIGGERS_RTO | USABLE_BY_BUYER_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        ITEM_NOT_AVAILABLE(~TRIGGERS_RTO | USABLE_BY_SELLER_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | PART_CANCEL_APPLICABLE),
        ITEM_PRICE_TOO_HIGH(~TRIGGERS_RTO | USABLE_BY_BUYER_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        DEPRECATED_DELAYED_DELIVERY(~TRIGGERS_RTO | USABLE_BY_BUYER_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        REJECT_ORDER(~TRIGGERS_RTO|USABLE_BY_SELLER_PARTY|SELLER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),

        DELAYED_DELIVERY(~TRIGGERS_RTO|USABLE_BY_BUYER_PARTY|SELLER_PARTY_RESPONSIBLE_FOR_LOSSES|LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        INVALID_HOLE_IN_REASON_CODES(0),
        DELAYED_ORDER_PICKUP(~TRIGGERS_RTO | USABLE_BY_LOGISTICS_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        ITEM_MISMATCH(TRIGGERS_RTO|USABLE_BY_BUYER_PARTY|SELLER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        BUYER_WANTS_TO_MODIFY(TRIGGERS_RTO|USABLE_BY_BUYER_PARTY|BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),

        BUYER_CANNOT_BE_CONTACTED(TRIGGERS_RTO|USABLE_BY_LOGISTICS_PARTY|USABLE_BY_SELLER_PARTY|BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        ITEM_NOT_REQUIRED(TRIGGERS_RTO| USABLE_BY_SELLER_PARTY | USABLE_BY_LOGISTICS_PARTY| USABLE_BY_BUYER_PARTY| BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|PART_CANCEL_APPLICABLE),
        BUYER_REFUSES_DELIVERY(TRIGGERS_RTO| USABLE_BY_SELLER_PARTY | USABLE_BY_LOGISTICS_PARTY| BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        INVALID_ADDRESS(TRIGGERS_RTO| USABLE_BY_SELLER_PARTY | USABLE_BY_LOGISTICS_PARTY| BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        BUYER_UNAVAILABLE_TO_TAKE_DELIVERY(TRIGGERS_RTO| USABLE_BY_SELLER_PARTY | USABLE_BY_LOGISTICS_PARTY| BUYER_PARTY_RESPONSIBLE_FOR_LOSSES|~PART_CANCEL_APPLICABLE),
        ACT_OF_GOD(~TRIGGERS_RTO|USABLE_BY_LOGISTICS_PARTY|USABLE_BY_SELLER_PARTY| LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES| SELLER_PARTY_RESPONSIBLE_FOR_LOSSES| ~PART_CANCEL_APPLICABLE),
        DELIVERY_NOT_POSSIBLE(~TRIGGERS_RTO | USABLE_BY_LOGISTICS_PARTY | USABLE_BY_SELLER_PARTY | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        DELIVERY_PINCODE_NOT_SERVICEABLE(~TRIGGERS_RTO | USABLE_BY_SELLER_PARTY  | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        PICKUP_PINCODE_NOT_SERVICEABLE(~TRIGGERS_RTO | USABLE_BY_SELLER_PARTY  | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        ORDER_LOST_INTRANSIT(~TRIGGERS_RTO | USABLE_BY_SELLER_PARTY | USABLE_BY_LOGISTICS_PARTY  | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | LOGISTICS_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),
        PACKED_ORDER_INCOMPLETE(~TRIGGERS_RTO | USABLE_BY_LOGISTICS_PARTY  | SELLER_PARTY_RESPONSIBLE_FOR_LOSSES | ~PART_CANCEL_APPLICABLE),

        ;




        final int bits;
        CancellationReasonCode(int bits){
            this.bits = bits;
        }

        public boolean isUsableByBuyerParty(){
            return (bits & USABLE_BY_BUYER_PARTY) > 0;
        }

        public boolean isUsedForReturns(){
            return (bits & TRIGGERS_RTO) > 0;
        }

        public static final EnumConvertor<CancellationReasonCode> convertor = new OrdinalBasedEnumConvertor<>(CancellationReasonCode.class);
    }
}
